FROM python:3.9

RUN pip install --upgrade pip

RUN pip install mysql-connector-python-rf

RUN pip install --upgrade mysql-connector-python

WORKDIR /usr/app/src

COPY hello_world.py .

CMD ["python", "hello_world.py"]
